#pragma once

#define DISTRHO_PLUGIN_BRAND "Alza Audio"
#define DISTRHO_PLUGIN_NAME "Aurora Uplift"
#define DISTRHO_PLUGIN_URI "urn:alza-audio:aurora-uplift-vst2"
#define DISTRHO_PLUGIN_CLAP_ID "com.alzaaudio.aurorauplift"

#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_IS_SYNTH 1
#define DISTRHO_PLUGIN_HAS_UI 0
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_PROGRAMS 0
#define DISTRHO_PLUGIN_WANT_STATE 0
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 0
